include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    - sort_constructors_first
    - prefer_single_quotes
    - lines_longer_than_80_chars
    - public_member_api_docs
